import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Sidebar
    admin: "ADMIN",
    superAdmin: "Super Admin",
    principal: "MAIN",
    overview: "Overview",
    reports: "Reports",
    users: "Users",
    partners: "Partners",
    community: "COMMUNITY",
    localMissions: "Local Missions",
    collectionPoints: "Collection Points",
    economy: "ECONOMY",
    pointsSystem: "Points System",
    physicalItems: "Physical Items",
    donations: "Donations",
    crowdfunding: "Crowdfunding",
    config: "CONFIG",
    analytics: "Analytics",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    shopifyProducts: "Shopify Products",
    "validation-donations": "Donation Proofs",
    allCollections: "All Collections",
    pending: "Pending",
    rejected: "Rejected",
    // Common UI
    searchPlaceholder: "Search...",
    sortBy: "SORT BY:",
    dateLabel: "DATE",
    statusLabel: "STATUS",
    actionsLabel: "ACTIONS",
    previous: "Previous",
    next: "Next",
    showing: "Showing",
    to: "to",
    of: "of",
    results: "results",
    allCategories: "All categories",
    allTypes: "All types",
    allStatuses: "All statuses",
    dateDesc: "Date (Newest)",
    dateAsc: "Date (Oldest)",
    nameAsc: "Name (A-Z)",
    nameDesc: "Name (Z-A)",
    emailAsc: "Email (A-Z)",
    companyAsc: "Company (A-Z)",
    ptsDesc: "Points (Highest)",
    ptsAsc: "Points (Lowest)",
    noItemsFound: "No items found.",
    noRequestsFound: "No requests found.",
    noReportsFound: "No reports found.",
    noUsersFound: "No users found matching your criteria.",
    noPartnersFound: "No partners found.",
    noPartnersPending: "No pending partners.",
    noMissionsFound: "No missions found.",
    searchPartnerPlaceholder: "Search for a partner...",
    allSpecies: "All species",
    titleAsc: "Title (A-Z)",
    titleDesc: "Title (Z-A)",
    globalConfig: "Global Configuration",
    configUpdateMsg: "Changes to the scale will be applied immediately for all future user actions. Existing points will not be affected.",
    clickToSimulate: "Click to enable/disable a rule (simulation)",
    boosterTitle: "Boost donations this weekend?",
    boosterDesc: "Enable a x2 multiplier on all physical donation deposits to encourage the SPA.",
    activateNow: "ACTIVATE NOW",
    currentValuePerAction: "Current value per action",
    thisMonth: "This month",
    converted: "Converted",
    unused: "Unused",
    activePointsLabel: "active collection points",
    goal: "goal",
    of: "of",
    noDescription: "No description",
    noComments: "No comments yet.",
    noNotifHistory: "No notification history.",
    noAddress: "No address",
    noDataFound: "No data found.",
    updating: "Updating...",
    // Statuses
    active: "Active",
    inactive: "Inactive",
    suspended: "Suspended",
    banned: "Banned",
    pending: "Pending",
    rejected: "Rejected",
    lost: "Lost",
    sighted: "Sighted",
    resolved: "Resolved",
    found: "Found",
    rescued: "Rescued",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    approved: "Approved",
    // Validation Donations
    physicalDonationLabel: "Physical Donation",
    unknownPoint: "Unknown point",
    ptsToAttribute: "Points to attribute",
    declaredQuantity: "Declared quantity:",
    toValidate: "to validate",
    vsLastMonth: "vs last month",
    loadingLabel: "Loading...",
    validateDonationTitle: "Validate Donation",
    rejectDonationTitle: "Reject Donation",
    optionalNote: "Note (Optional)",
    rejectionReason: "Reason for rejection",
    food: "Food",
    litter: "Litter",
    toys: "Toys & accessories",
    medicine: "Medicine / care",
    other: "Other",
    blurredPhoto: "Blurred or unreadable photo",
    itemNotVisible: "Item not visible on photo",
    pointNotRecognized: "Collection point not recognized",
    // Login
    loginTitle: "Log in",
    emailLabel: "Email",
    passwordLabel: "Password",
    rememberMe: "Keep me signed in",
    forgotPassword: "Forgotten password",
    signInBtn: "Sign In",
    signingIn: "Signing in...",
    adminOnly: "Admin access only",
    welcomeBack: "Welcome back",
    loginFailed: "Login failed. Check your credentials.",
    networkError: "Network error. Please try again.",
    enterEmail: "Enter my email",
    enterPassword: "Enter my password",
    fillAllFields: "Please fill in all fields.",
    accessDeniedAdmin: "Access denied. Admin accounts only.",
    // Topbar
    dashboardSub: "Dashboard — Hesteka Admin",
    newReport: "New Report",
    viewAll: "View All",
    noNotifs: "No recent notifications",
    // Profile Modal
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    company: "Company",
    address: "Address",
    bioIntro: "Bio / Intro",
    bioPlaceholder: "Write something about yourself...",
    close: "Close",
    cancel: "Cancel",
    saveProfile: "Save Profile",
    saving: "Saving...",
    // Stats
    usersLabel: "USERS",
    activeReports: "ACTIVE REPORTS",
    resolved: "RESOLVED",
    donationsCollected: "DONATIONS COLLECTED",
    pointsDistributed: "POINTS DISTRIBUTED",
    partnersLabel: "PARTNERS",
    activeMissions: "ACTIVE MISSIONS",
    downloads: "DOWNLOADS",
    // Sub stats
    thisWeek: "this week",
    pending: "pending",
    rate: "Rate",
    thisMonth206: "this month",
    pendingPoints: "pending",
    inValidation: "in validation",
    inProgress: "in progress",
    thisMonth55: "this month",
    // Map
    mapTitle: "Reports Map",
    view: "View",
    activeReportsCount: "active reports",
    // Activity
    recentActivity: "Recent Activity",
    act1: "lost dog report, Salon-de-Provence",
    act1time: "2 min ago",
    act2: "just registered",
    act2time: "8 min ago",
    act3: "20\u20AC donation received \u2013 Mission SPA Salon",
    act3time: "15 min ago",
    act4: "SPA Salon validated 4 participations for Dogs Walk mission",
    act4time: "22 min ago",
    act5: "report resolved \u2705",
    act5time: "1h ago",
    whiteKitten: "White Kitten",
    // Chart
    reportTypes: "Report Types",
    lost: "Lost",
    found: "Found",
    sheltered: "Sheltered",
    injured: "Injured",
    // Crowdfunding
    goal: "/ 5,000\u20AC goal",
    donors: "Donors",
    remaining: "Remaining",
    left: "Left",
    // Signalements Page
    reportsTitle: "Reports",
    reportsSub: "89 active - 342 resolved",
    totalActive: "TOTAL ACTIVE",
    resolvedLabel: "RESOLVED",
    pendingLabel: "PENDING",
    resolutionRate: "RESOLUTION RATE",
    allReports: "All Reports",
    animal: "ANIMAL",
    type: "TYPE",
    status: "STATUS",
    location: "LOCATION",
    user: "USER",
    date: "DATE",
    actions: "ACTIONS",
    viewBtn: "View",
    editBtn: "Edit",
    deleteBtn: "Delete",
    validateBtn: "Validate",
    spamBtn: "Spam",
    // Users Page
    usersTitle: "Users",
    usersSub: "1,284 registered",
    totalRegistered: "TOTAL REGISTERED",
    activeLabel: "ACTIVE",
    suspendedLabel: "SUSPENDED",
    newThisMonth: "NEW THIS MONTH",
    allUsers: "All Users",
    email: "EMAIL",
    points: "POINTS",
    missions: "MISSIONS",
    registration: "REGISTRATION",
    detailsBtn: "Details",
    suspendBtn: "Suspend",
    reactivateBtn: "Reactivate",
    banBtn: "Ban",
    exportBtn: "Export",
    // Partners Page
    partnersTitle: "Partners",
    partnersSub: "14 active - 3 pending",
    pendingValidation: "Pending Validation",
    activePartners: "Active Partners",
    pendingMissionValidations: "Pending Mission Validations",
    participants: "PARTICIPANTS",
    validateAll: "Validate All",
    addPartner: "Add Partner",
    // Missions Page
    missionsTitle: "Local Missions",
    missionsSub: "8 missions - 2 in progress",
    inProgressLabel: "IN PROGRESS",
    toComeLabel: "TO COME",
    finishedLabel: "FINISHED",
    pointsAttributed: "POINTS ATTRIBUTED",
    allMissions: "All Missions",
    createMission: "Create Mission",
    cancelBtn: "Cancel",
    // Points de collecte Page
    collectionPointsTitle: "Collection Points",
    collectionPointsSub: "22 active points",
    pointsList: "List of collection points",
    addPoint: "Add point",
    deactivateBtn: "Deactivate",
    // Points Page
    pointsTitle: "Points System",
    pointsSub: "18,450 pts distributed",
    distributedLabel: "DISTRIBUTED",
    exchangedLabel: "EXCHANGED",
    expiredLabel: "EXPIRED",
    pointsScale: "Points Scale",
    usageRules: "Usage Rules",
    transactionHistory: "Transaction History",
    saveScale: "Save Scale",
    saveBtn: "Save",
    validityDuration: "Validity duration - 12 months",
    monthlyCeiling: "Monthly ceiling - 500 pts",
    doublePoints: "Double points active",
    pointsOnDonations: "Points on donations",
    // Physical Items Page
    itemsTitle: "Physical Items",
    itemsSub: "Exchangeable catalog",
    addItem: "Add an item",
    exchangeRequests: "Exchange Requests",
    article: "ARTICLE",
    address: "ADDRESS",
    shippedBtn: "Shipped",
    restockBtn: "Restock",
    outOfStock: "Out of Stock",
    // Donations Page
    donationsTitle: "Donations",
    donationsSub: "4,820\u20AC collected",
    totalCollected: "TOTAL COLLECTED",
    returnedAssos: "RETURNED TO ASSOS",
    averageBasket: "AVERAGE BASKET",
    allTransactions: "All Transactions",
    donator: "DONATOR",
    amount: "AMOUNT",
    association: "ASSOCIATION",
    fiscalReceipt: "Fiscal receipt",
    returnBtn: "Return",
    receiptBtn: "Receipt",
    // Crowdfunding Page
    crowdTitle: "Crowdfunding",
    crowdSub: "Ulule campaign - 83% reached",
    viewOnUlule: "View on Ulule",
    donorsList: "Donors List",
    counterpart: "COUNTERPART",
    confirmed: "Confirmed",
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSub: "Global performance",
    sessionsMonth: "SESSIONS/MONTH",
    retention: "RETENTION",
    avgDuration: "AVG DURATION",
    conversion: "CONVERSION",
    reportsMonth: "Reports per month",
    activeZones: "Most active zones",
    // Notifications Page
    notifTitle: "Notifications",
    notifSub: "Community alerts",
    createAlert: "Create an alert",
    geoTarget: "GEOGRAPHIC TARGETING",
    userType: "USER TYPE",
    message: "MESSAGE",
    sendAlert: "Send alert",
    notifHistory: "Notification history",
    // Settings Page
    settingsTitle: "Settings",
    settingsSub: "Platform configuration",
    adminTeam: "Admin Team",
    application: "Application",
    recentLogins: "Recent Logins",
    inviteAdmin: "Invite an admin",
    autoAlerts: "Automatic alerts",
    pushNotifs: "Push notifs enabled",
    maintenanceMode: "Maintenance mode",
    disableAccess: "Disables user access",
    alertRadius: "Alert radius",
    defaultGeo: "Default geolocation",
    saveChanges: "Save changes",
    superAdminBadge: "SUPER ADMIN",
    // Validation Dons Page
    valDonationsTitle: "Donation Proofs",
    valDonationsSub: "4 donations pending validation",
    pendingValidationDon: "PENDING",
    validatedThisMonth: "VALIDATED THIS MONTH",
    refused: "REFUSED",
    ptsGranted: "PTS GRANTED",
    howItWorks: "How it works?",
    howItWorksDesc: "The user takes a photo of their deposit in a partner collection point and submits it via the app. You validate or refuse here. Points (+15 pts) are automatically attributed after validation.",
    donsPendingVal: "Donations pending validation",
    recentValidations: "Recent validations",
    depositsThisMonth: "Deposits this month",
    refusalReasons: "Frequent refusal reasons",
    validatePts: "Validate +15 pts",
    refuseBtn: "Refuse",
    enlargePhoto: "Enlarge photo",
    validateAllDon: "Validate all",
  },
  fr: {
    admin: "ADMIN",
    superAdmin: "Super Admin",
    principal: "PRINCIPAL",
    overview: "Vue globale",
    reports: "Signalements",
    users: "Utilisateurs",
    partners: "Partenaires",
    community: "COMMUNAUT\u00C9",
    localMissions: "Missions locales",
    collectionPoints: "Points de collecte",
    economy: "\u00C9CONOMIE",
    pointsSystem: "Syst\u00E8me de points",
    physicalItems: "Articles physiques",
    donations: "Dons",
    crowdfunding: "Crowdfunding",
    config: "CONFIG",
    analytics: "Analytics",
    notifications: "Notifications",
    settings: "Param\u00E8tres",
    logout: "D\u00E9connexion",
    shopifyProducts: "Produits Shopify",
    "validation-donations": "Preuves de Don",
    allCollections: "Toutes les collections",
    pending: "En attente",
    rejected: "Rejeté",
    // Common UI
    searchPlaceholder: "Rechercher...",
    sortBy: "TRIER PAR:",
    dateLabel: "DATE",
    statusLabel: "STATUT",
    actionsLabel: "ACTIONS",
    previous: "Pr\u00E9c\u00E9dent",
    next: "Suivant",
    showing: "Affichage de",
    to: "\u00E0",
    of: "sur",
    results: "r\u00E9sultats",
    allCategories: "Toutes les cat\u00E9gories",
    allTypes: "Tous les types",
    allStatuses: "Tous les statuts",
    dateDesc: "Date (Plus r\u00E9cent)",
    dateAsc: "Date (Plus ancien)",
    nameAsc: "Nom (A-Z)",
    nameDesc: "Nom (Z-A)",
    emailAsc: "Email (A-Z)",
    companyAsc: "Entreprise (A-Z)",
    ptsDesc: "Points (Plus \u00E9lev\u00E9)",
    ptsAsc: "Points (Plus bas)",
    noItemsFound: "Aucun article trouv\u00E9.",
    noRequestsFound: "Aucune demande trouv\u00E9e.",
    noReportsFound: "Aucun signalement trouv\u00E9.",
    noUsersFound: "Aucun utilisateur trouv\u00E9 correspondant \u00E0 vos crit\u00E8res.",
    noPartnersFound: "Aucun partenaire trouv\u00E9.",
    noPartnersPending: "Aucun partenaire en attente.",
    noMissionsFound: "Aucune mission trouv\u00E9e.",
    searchPartnerPlaceholder: "Rechercher un partenaire...",
    allSpecies: "Toutes les esp\u00E8ces",
    titleAsc: "Titre (A-Z)",
    titleDesc: "Titre (Z-A)",
    globalConfig: "Configuration Globale",
    configUpdateMsg: "Les modifications apport\u00E9es au bar\u00E8me seront appliqu\u00E9es imm\u00E9diatement pour toutes les futures actions des utilisateurs. Les points d\u00E9j\u00E0 acquis ne seront pas impact\u00E9s.",
    clickToSimulate: "Cliquez pour activer/d\u00E9sactiver une r\u00E8gle (simulation)",
    boosterTitle: "Booster les dons ce weekend ?",
    boosterDesc: "Activez un multiplicateur x2 sur tous les d\u00E9p\u00F4ts de dons physiques pour encourager la SPA.",
    activateNow: "ACTIVER MAINTENANT",
    currentValuePerAction: "Valeur actuelle par action",
    thisMonth: "Ce mois",
    converted: "Convertis",
    unused: "Non utilis\u00E9s",
    activePointsLabel: "points de collecte actifs",
    goal: "objectif",
    of: "sur",
    noDescription: "Aucune description",
    noComments: "Aucun commentaire pour le moment.",
    noNotifHistory: "Aucun historique de notification.",
    noAddress: "Aucune adresse",
    noDataFound: "Aucune donn\u00E9e trouv\u00E9e.",
    updating: "Mise \u00E0 jour...",
    // Statuses
    active: "Actif",
    inactive: "Inactif",
    suspended: "Suspendu",
    banned: "Banni",
    pending: "En attente",
    rejected: "Rejet\u00E9",
    lost: "Perdu",
    sighted: "Signal\u00E9",
    resolved: "R\u00E9solu",
    found: "Trouv\u00E9",
    rescued: "Sauv\u00E9",
    shipped: "Exp\u00E9di\u00E9",
    delivered: "Livr\u00E9",
    cancelled: "Annul\u00E9",
    approved: "Approuv\u00E9",
    // Validation Donations
    physicalDonationLabel: "Donation physique",
    unknownPoint: "Point inconnu",
    ptsToAttribute: "Points \u00E0 attribuer",
    declaredQuantity: "Quantit\u00E9 d\u00E9clar\u00E9e :",
    toValidate: "\u00E0 valider",
    vsLastMonth: "vs mois d\u00E9rn.",
    loadingLabel: "Chargement...",
    validateDonationTitle: "Valider la donation",
    rejectDonationTitle: "Refuser la donation",
    optionalNote: "Note (Optionnel)",
    rejectionReason: "Raison du refus",
    food: "Croquettes / nourriture",
    litter: "Liti\u00E8re",
    toys: "Jouets & accessoires",
    medicine: "M\u00E9dicaments / soins",
    other: "Autre",
    blurredPhoto: "Photo floue ou illisible",
    itemNotVisible: "D\u00E9p\u00F4t non visible sur la photo",
    pointNotRecognized: "Point de collecte non reconnu",
    // Login
    loginTitle: "Connexion",
    emailLabel: "E-mail",
    passwordLabel: "Mot de passe",
    rememberMe: "Rester connect\u00E9",
    forgotPassword: "Mot de passe oubli\u00E9",
    signInBtn: "Se connecter",
    signingIn: "Connexion en cours...",
    adminOnly: "Acc\u00E8s administrateur uniquement",
    welcomeBack: "Bon retour",
    loginFailed: "Échec de la connexion. Vérifiez vos identifiants.",
    networkError: "Erreur réseau. Veuillez réessayer.",
    enterEmail: "Entrez mon e-mail",
    enterPassword: "Entrez mon mot de passe",
    fillAllFields: "Veuillez remplir tous les champs.",
    accessDeniedAdmin: "Acc\u00E8s refus\u00E9. Comptes administrateurs uniquement.",
    dashboardSub: "Tableau de bord \u2014 Hesteka Admin",
    newReport: "Nouveau signalement",
    viewAll: "Voir tout",
    noNotifs: "Aucune notification r\u00E9cente",
    firstName: "Pr\u00E9nom",
    lastName: "Nom",
    phone: "T\u00E9l\u00E9phone",
    company: "Entreprise",
    address: "Adresse",
    bioIntro: "Bio / Pr\u00E9sentation",
    bioPlaceholder: "\u00C9crivez quelque chose sur vous...",
    close: "Fermer",
    cancel: "Annuler",
    saveProfile: "Enregistrer le profil",
    saving: "Enregistrement...",
    usersLabel: "UTILISATEURS",
    activeReports: "SIGNALEMENTS ACTIFS",
    resolved: "R\u00C9SOLUS",
    donationsCollected: "DONS COLLECT\u00C9S",
    pointsDistributed: "POINTS DISTRIBU\u00C9S",
    partnersLabel: "PARTENAIRES",
    activeMissions: "MISSIONS ACTIVES",
    downloads: "T\u00C9L\u00C9CHARGEMENTS",
    thisWeek: "cette sem.",
    pending: "en attente",
    rate: "Taux",
    thisMonth206: "ce mois",
    pendingPoints: "en attente",
    inValidation: "en validation",
    inProgress: "en cours",
    thisMonth55: "ce mois",
    mapTitle: "Carte signalements",
    view: "Lire",
    activeReportsCount: "signalements actifs",
    recentActivity: "Activit\u00E9 r\u00E9cente",
    act1: "signalement chien perdu, Salon-de-Provence",
    act1time: "Il y a 2 min",
    act2: "vient de s'inscrire",
    act2time: "Il y a 8 min",
    act3: "Don de 20\u20AC re\u00E7u \u2013 Mission SPA Salon",
    act3time: "Il y a 15 min",
    act4: "SPA Salon a valid\u00E9 4 participations mission Balade chiens",
    act4time: "Il y a 22 min",
    act5: "signalement r\u00E9solu \u2705",
    act5time: "Il y a 1h",
    whiteKitten: "Chaton blanc",
    reportTypes: "Types de signalements",
    lost: "Perdus",
    found: "Trouvés",
    sheltered: "Recueillis",
    injured: "Blessés",
    goal: "/ 5 000\u20AC objectif",
    donors: "Donateurs",
    remaining: "Restants",
    left: "Restant",
    // Signalements Page
    reportsTitle: "Signalements",
    reportsSub: "signalements actifs - r\u00E9solus",
    totalActive: "TOTAL ACTIFS",
    resolvedLabel: "R\u00C9SOLUS",
    pendingLabel: "EN ATTENTE",
    resolutionRate: "TAUX R\u00C9SOLUTION",
    allReports: "Tous les signalements",
    animal: "ANIMAL",
    type: "TYPE",
    status: "STATUT",
    location: "LOCALISATION",
    user: "UTILISATEUR",
    date: "DATE",
    actions: "ACTIONS",
    viewBtn: "Voir",
    editBtn: "Modifier",
    deleteBtn: "Supprimer",
    validateBtn: "Valider",
    spamBtn: "Spam",
    // Users Page
    usersTitle: "Utilisateurs",
    usersSub: "1 284 inscrits",
    totalRegistered: "TOTAL INSCRITS",
    activeLabel: "ACTIFS",
    suspendedLabel: "SUSPENDUS",
    newThisMonth: "NOUVEAUX CE MOIS",
    allUsers: "Tous les utilisateurs",
    email: "EMAIL",
    points: "POINTS",
    missions: "MISSIONS",
    registration: "INSCRIPTION",
    detailsBtn: "Fiche",
    suspendBtn: "Suspendre",
    reactivateBtn: "R\u00E9activer",
    banBtn: "Bannir",
    exportBtn: "Exporter",
    // Partners Page
    partnersTitle: "Partenaires",
    partnersSub: "14 actifs - 3 en attente",
    pendingValidation: "En attente de validation",
    activePartners: "Partenaires actifs",
    pendingMissionValidations: "Validations missions en attente",
    participants: "PARTICIPANTS",
    validateAll: "Valider tout",
    addPartner: "Ajouter un partenaire",
    // Missions Page
    missionsTitle: "Missions locales",
    missionsSub: "8 missions - 2 en cours",
    inProgressLabel: "EN COURS",
    toComeLabel: "\u00C0 VENIR",
    finishedLabel: "TERMIN\u00C9ES",
    pointsAttributed: "PTS ATTRIBU\u00C9S",
    allMissions: "Toutes les missions",
    createMission: "Cr\u00E9er une mission",
    cancelBtn: "Annuler",
    // Points de collecte Page
    collectionPointsTitle: "Points de collecte",
    collectionPointsSub: "22 points actifs",
    pointsList: "Liste des points de collecte",
    addPoint: "Ajouter un point",
    deactivateBtn: "D\u00E9sactiver",
    // Points Page
    pointsTitle: "Syst\u00E8me de points",
    pointsSub: "18 450 pts distribu\u00C9S",
    distributedLabel: "DISTRIBU\u00C9S",
    exchangedLabel: "\u00C9CHANG\u00C9S",
    expiredLabel: "EXPIR\u00C9S",
    pointsScale: "Bar\u00E8me des points",
    usageRules: "R\u00E8gles d'utilisation",
    transactionHistory: "Historique des transactions",
    saveScale: "Enregistrer le bar\u00E8me",
    saveBtn: "Enregistrer",
    validityDuration: "Dur\u00E9e de validit\u00E9 - 12 mois",
    monthlyCeiling: "Plafond mensuel - 500 pts",
    doublePoints: "Double points actif",
    pointsOnDonations: "Points sur dons",
    // Physical Items Page
    itemsTitle: "Articles physiques",
    itemsSub: "Catalogue \u00E9changeable",
    addItem: "Ajouter un article",
    exchangeRequests: "Demandes d'\u00E9change",
    article: "ARTICLE",
    address: "ADRESSE",
    shippedBtn: "Exp\u00E9di\u00E9",
    restockBtn: "R\u00E9appro",
    outOfStock: "Rupture",
    // Donations Page
    donationsTitle: "Dons",
    donationsSub: "4 820\u20AC collect\u00E9s",
    totalCollected: "TOTAL COLLECT\u00C9",
    returnedAssos: "REVERS\u00C9 ASSOS",
    averageBasket: "PANIER MOYEN",
    allTransactions: "Toutes les transactions",
    donator: "DONATEUR",
    amount: "MONTANT",
    association: "ASSOCIATION",
    fiscalReceipt: "Re\u00E7u fiscal",
    returnBtn: "Reverser",
    receiptBtn: "Re\u00E7u",
    // Crowdfunding Page
    crowdTitle: "Crowdfunding",
    crowdSub: "Campagne Ulule - 83% atteint",
    viewOnUlule: "Voir sur Ulule",
    donorsList: "Liste des donateurs",
    counterpart: "CONTREPARTIE",
    confirmed: "Confirm\u00E9",
    // Analytics Page
    analyticsTitle: "Analytics",
    analyticsSub: "Performances globales",
    sessionsMonth: "SESSIONS/MOIS",
    retention: "R\u00C9TENTION",
    avgDuration: "DUR\u00C9E MOY.",
    conversion: "CONVERSION",
    reportsMonth: "Signalements par mois",
    activeZones: "Zones les plus actives",
    // Notifications Page
    notifTitle: "Notifications",
    notifSub: "Alertes communaut\u00E9",
    createAlert: "Cr\u00E9er une alerte",
    geoTarget: "CIBLAGE G\u00C9OGRAPHIQUE",
    userType: "TYPE D'UTILISATEURS",
    message: "MESSAGE",
    sendAlert: "Envoyer l'alerte",
    notifHistory: "Historique des notifications",
    // Settings Page
    settingsTitle: "Param\u00E8tres",
    settingsSub: "Configuration de la plateforme",
    adminTeam: "\u00C9quipe admin",
    application: "Application",
    recentLogins: "Derni\u00E8res connexions",
    inviteAdmin: "Inviter un admin",
    autoAlerts: "Alertes automatiques",
    pushNotifs: "Notifs push activ\u00E9es",
    maintenanceMode: "Mode maintenance",
    disableAccess: "D\u00E9sactive l'acc\u00E8s utilisateurs",
    alertRadius: "Rayon d'alerte",
    defaultGeo: "G\u00E9olocalisation par d\u00E9faut",
    saveChanges: "Enregistrer les modifications",
    superAdminBadge: "SUPER ADMIN",
    // Validation Dons Page
    valDonationsTitle: "Preuves de Don",
    valDonationsSub: "4 dons en attente de validation",
    pendingValidationDon: "EN ATTENTE",
    validatedThisMonth: "VALID\u00C9S CE MOIS",
    refused: "REFUS\u00C9S",
    ptsGranted: "PTS ACCORD\u00C9S",
    howItWorks: "Comment \u00E7a fonctionne ?",
    howItWorksDesc: "L'utilisateur prend une photo de son d\u00E9p\u00F4t dans un point de collecte partenaire et la soumet via l'appli. Tu valides ou refuses ici. Les points (+15 pts) sont attribu\u00E9s automatiquement apr\u00E8s validation.",
    donsPendingVal: "Dons en attente de validation",
    recentValidations: "Validations r\u00E9centes",
    depositsThisMonth: "Stats d\u00E9p\u00F4ts ce mois",
    refusalReasons: "Motifs de refus fr\u00E9quents",
    validatePts: "Valider +15 pts",
    refuseBtn: "Refuser",
    enlargePhoto: "Agrandir la photo",
    validateAllDon: "Tout valider",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
